### PR TITLE
242 update filter_panel vignette with shinyjs::useShinyjs

### LINKED ISSUE #242: Update example in vignette
The team looked into this together and it was working just fine using the `filter_panel_refactor@main` once we add the `useShinyjs()` after the `fluidPage`

```r
app <- shinyApp(
  ui = fluidPage( #here
    shinyjs::useShinyjs(),
    fluidRow(
      column(
        width = 9,
        id = "teal_primary_col",
...
```
We need to update the example to include have `useShinyjs()`.
Case closed for this ticket and open a new one for updating the vignette.

_Originally posted by @donyunardi in https://github.com/insightsengineering/teal.slice/issues/157#issuecomment-1499489662_

### PR DESCRIPTION
**Pull request by m7pr**
close #242

### CODE REVIEW

**Comment by chlebowa** [comment]
Can you please also update the app in the other vignette?

**Comment by chlebowa** [comment]
By the way, can we enhance the code blocks so that they have "copy" buttons? This might be a separate issue, granted, but a very simple one.

**Comment by m7pr** [comment]
@chlebowa I was thinking the same, however pkgdown websites does that for us automatically right? But it needs to be parsed by pkgdown and uploaded as a site?

**Comment by m7pr** [comment]
@chlebowa yeah, check this out this pkgdown article https://insightsengineering.github.io/teal.slice/latest-tag/articles/filter-panel.html where you have copy buttons on the right corner of each chunk, if you hover on the chunk.

image

If you'd like to add a custom button, then for pkgdown websites we would have 2 buttons : P and that's weird.
I suspect our grand entrance area is pkgdown website and we are expecting people to view it more often than regular vignettes, as on the pkgdown website we do also have package README and function's reference.

Lastly I think it could be executed with a one-liner but only if you add another dependency to the package, which is not worth it in my opinion. If you'd like to talk more, we can start a Discussion in Discussion section?

**Review by donyunardi — CHANGES_REQUESTED** [review]
Upon executing the example script, it appears that the functionality of the "Remove iris@Species filter" button is no longer functioning. The root cause of this issue lies within the if statement found in the following line:

https://github.com/insightsengineering/teal.slice/blob/2a8323ab2edb2bce3b3fe79f8a20ee2af1c9814e/vignettes/filter-panel.Rmd#L388-L389

As a result of the `filter_panel_refactor`, `get_filter_state` now returns a `teal_slice` object. Due to the change in object structure, we need to modify this specific line during the update.

I tried this and it works:
```r
if (!is.null(states) && states[[1]]$dataname == "iris" && states[[1]]$varname == "Species") {  
```

**Comment by donyunardi** [comment]
> If you'd like to add a custom button, then for pkgdown websites we would have 2 buttons : P and that's weird. I suspect our grand entrance area is pkgdown website and we are expecting people to view it more often than regular vignettes, as on the pkgdown website we do also have package README and function's reference.

I concur with this viewpoint. Having two separate buttons for copying would be odd, and it would be challenging to devise a mechanism to enable or disable them individually.

**Comment by m7pr** [comment]
@donyunardi on which branches were you testing it? I tried to run it on main as this actually should be a quick update to main, even though we provided a PR to filter_panel_refactor so that we do not merge filter_panel_refactor to the main. Should we create a separate issue for fixing vignettes at all, before merging filter_panel_refactor into main?

**Comment by chlebowa** [comment]
I agree, there's no use grappling with the copy buttons.

This can't go into main because it uses `teal_slice`s. I'll have a look at Dony's bug.

**Comment by m7pr** [comment]
thanks @chlebowa

**Comment by chlebowa** [comment]
It seems to me the `if` can go altogether. The new api does not crash when one attempts to remove a non-existent filter state.

**Comment by m7pr** [comment]
hey thanks for the input. I'll try incorporating that into the vignette

**Comment by m7pr** [comment]
test message from Git Kraken

**Comment by donyunardi** [comment]
> @donyunardi on which branches were you testing it? I tried to run it on main as this actually should be a quick update to main, even though we provided a PR to filter_panel_refactor so that we do not merge filter_panel_refactor to the main. Should we create a separate issue for fixing vignettes at all, before merging filter_panel_refactor into main?

The base branch of this PR is pointing to filter_panel_refactor@main so I thought I should test it using that branch.

**Comment by m7pr** [comment]
Great, thanks. All clear

**Comment by m7pr** [comment]
Hey @chlebowa it works with your proposed changes - thanks. I just wanted to double check the expected behavior. If no filter is used then we present NULL and NULL, if one filter is selected then we present a NULL and a list with a filter code (?) and if two filters are present then we show the filter code. Check below video and the text area that shows the code used for the analysis
https://github.com/insightsengineering/teal.slice/assets/133694481/6abb9dde-32d2-4343-a255-78368bb811f8

**Comment by m7pr** [comment]
https://github.com/insightsengineering/teal.slice/assets/133694481/745fd618-7e7e-440e-a88e-e1d53fb46065

**Comment by chlebowa** [comment]
That panel contains the output of `FilteredData$get_call`, which returns a list of calls, one per data set. Those calls in turn are `NULL` if no observations are filtered out. This seems to correspond to what you see.

**Comment by m7pr** [comment]
@donyunardi let me know what you think on your end

**Review by donyunardi — APPROVED** [review]
LGTM!

**Pull request merged**
