### PR TITLE
fixing bug when adding filter again

### LINKED ISSUE #411: [Bug]: error occurs when adding, removing, and re-adding `COUNTRY` filter in exploratory app
**Summary:**
The `teal.gallery` exploratory app encounters an error when users repeatedly add, remove, and add back the` "COUNTRY"` filter in the "Data Table" tab.

**Description:**
In the `"Data Table"` tab, if a user adds the `"COUNTRY"` filter, then removes it using the` "{+}"` widget (Available filters), and finally adds it back, an error occurs.

Upon investigation, it was found that the function `private$get_choices()` from `FilterStateChoices `initially returns 10 elements: "CHN", "USA", "BRA", "PAK", "NGA", "RUS", "JPN", "GBR", "CAN", "CHE" with respective counts of 219, 40, 30, 31, 26, 19, 18, 9, 8, and 0.

However, when the filter is added back, it only returns 9 elements, excluding the "Country" with a count of 0.

**Steps to Reproduce:**

- Initialize the exploratory app from` teal.gallery.`
- Go to the "Data Table" tab.
- Select the "Country" filter from ADSL.
- Uncheck the "Country" filter from the "Available filters" (+ sign).
- Select the "Country" filter again.

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by gogonzo**
closes #411

### CODE REVIEW

**Comment by chlebowa** [comment]
Odd that I cannot reproduce the error in a small app with the `funny_module` and `iris`.
Also, I don't see how the `levels` call fixes the issue. When is `choices[choices %in% levels(private$x)]` different from `choices[choices %in% private$x]`?

**Comment by kartikeyakirar** [comment]
> Odd that I cannot reproduce the error in a small app with the funny_module and iris.
@chlebowa  could you share example you were testing

**Comment by chlebowa** [comment]
```
rm(list = ls())

options("teal.bs_theme" = bslib::bs_theme(version = 3))
devtools::load_all("../teal.slice")
devtools::load_all("../teal")
library(scda)

funny_module <- function (label = "Filter states", datanames = "all") {
  checkmate::assert_string(label)
  module(
    label = label,
    datanames = datanames,
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_states")),
        verbatimTextOutput(ns("filter_calls")),
        actionButton(ns("reset"), "reset_to_default")
      )
    },
    server = function(input, output, session, data, filter_panel_api) {
      checkmate::assert_class(data, "tdata")
      observeEvent(input$reset, set_filter_state(filter_panel_api, default_filters))
      output$filter_states <- renderText({
        logger::log_trace("rendering text1")
        stage1 <- filter_panel_api |> get_filter_state()
        stage2 <- lapply(stage1, as.list)
        stage3 <- yaml::as.yaml(stage2)
        stage3
      })
      output$filter_calls <- renderText({
        logger::log_trace("rendering text2")
        attr(data, "code")()
      })
    }
  )
}

Iris <- iris
levels(Iris$Species) #%<>% toupper()
Iris$Species2 <- Iris$Species
Iris$Species3 <- Iris$Species
Iris$Sepal.Length[1] <- NA
Iris$Sepal.Length[2] <- Inf
Iris$Species3[2] <- NA
attr(Iris[[1]], "label") <- "variable label"
attr(Iris[[2]], "label") <- "variable label"
attr(Iris[[3]], "label") <- "variable label"
attr(Iris[[4]], "label") <- "variable label"
data <- teal_data(
  dataset("iris", Iris),
  dataset("mtcars", mtcars)
)

default_filters <- teal_slices(
  count_type = NULL
)

app <- init(
  data = data,
  modules = list(funny_module(), funny_module("module2")), filter = default_filters
)

runApp(app, launch.browser = TRUE)
```

**Comment by gogonzo** [comment]
@chlebowa problem occurs when variable has more levels than actual values in a vector. I guess it's reproducible if you:
- extend Species levels by inexisting one
- run app
- add Species column
- remove Species filter
- add again

**Review by kartikeyakirar — APPROVED** [review]
checked the exploratory app. this issue is fixed.

**Comment by chlebowa** [comment]
> @chlebowa problem occurs when variable has more levels than actual values in a vector. I guess it's reproducible if you:

Indeed.

**Pull request merged**
