### PR TITLE
531 warning in example@pre release cleanup@main

### LINKED ISSUE #531: remove `filters for columns: ARRAY_TYPE excluded from mae` warning
Initially found https://github.com/insightsengineering/teal.slice/pull/506#discussion_r1462162016
This appears in examples for `FilteredData` and `MAEFilteredDataset`

### PR DESCRIPTION
**Pull request by gogonzo**
closes #531 
We used to distinguish sub-items of the MAE object by term `datalabel`. We don't do this anymore, this is artifact after the refactor.

### CODE REVIEW

**Comment by chlebowa** [comment]
I still get the warning
```
utils::data(miniACC, package = "MultiAssayExperiment")
datasets <- FilteredData$new(list(iris = iris, mae = miniACC))
fs <-
  teal_slices(
    teal_slice(
      dataname = "iris", varname = "Sepal.Length", selected = c(5.1, 6.4),
      keep_na = TRUE, keep_inf = FALSE
    ),
    teal_slice(
      dataname = "iris", varname = "Species", selected = c("setosa", "versicolor"),
      keep_na = FALSE
    ),
    teal_slice(
      dataname = "mae", varname = "years_to_birth", selected = c(30, 50),
      keep_na = TRUE, keep_inf = FALSE
    ),
    teal_slice(dataname = "mae", varname = "vital_status", selected = "1", keep_na = FALSE),
    teal_slice(dataname = "mae", varname = "gender", selected = "female", keep_na = TRUE),
    teal_slice(
      dataname = "mae", varname = "ARRAY_TYPE",
      selected = "", keep_na = TRUE, datalabel = "RPPAArray", arg = "subset"
    )
  )

datasets$set_filter_state(state = fs)
```

```
[WARN] 2024-01-25 14:52:19.0469 pid:79753 token:[] teal.slice filters for columns: ARRAY_TYPE excluded from mae
```

**Comment by gogonzo** [comment]
> I still get the warning
>     teal_slice(
>       dataname = "mae", varname = "ARRAY_TYPE",
>       selected = "", keep_na = TRUE, datalabel = "RPPAArray", arg = "subset"
>     )
>   )

Of course you have since you provide a wrong `teal_slice`. This is the change I've made in this PR - I replaced `datalabel =` in the example with `experiment =`. If you want to add filter for given experiment, please specify `experiment = ` (instead of `datalabel = `)

**Comment by chlebowa** [comment]
Of course. Sorry, I took the example from the old branch.

**Review by chlebowa — APPROVED** [review]
:ok_hand:

**Pull request merged**
