### PR TITLE
Move filter panel switch to active vars

### LINKED ISSUE #219: Move the global filter enable/disable button to Active Filter Variables card
> I like this one better, the check/cross mark coupled with the coloring will ensure no ambiguity. But consistency is also important - was there any discussion when selecting the toggle button for the entire filter panel or just chosen by whoever implemented it at the time? If the latter, can we switch the button for entire panel to be the same as above?
> 
> Also, on a more inquisitive look, does it actually make sense to place the filter panel toggle on the upper right corner? Perhaps it would it be more logical to place it inside the "Active Filter Variable" panel instead? image

@lcd2yyz I can't say whether there was a discussion or not for the main panel switch, I don't know. As far as location, yes I think it makes more sense in the Active Filter Variables section as well. I think this is outside the scope of the current issue so I opened #217. @donyunardi can we get this added on an upcoming sprint please.

_Originally posted by @asbates in https://github.com/insightsengineering/teal.slice/issues/207#issuecomment-1448452690_

### PR DESCRIPTION
**Pull request by asbates**
Moves the filter panel disable/enable switch into the active variables section.

Closes #219

### CODE REVIEW

**Comment by nikolas-burkoff** [comment]
Once you've disabled the filter panel you can still add a new filter which then appears - which is confusing

image

and then when you re-enable the filter panel the other filter that was there has vanished?

**Comment by asbates** [comment]
> Once you've disabled the filter panel you can still add a new filter which then appears - which is confusing
> 
> image
> 
> and then when you re-enable the filter panel the other filter that was there has vanished?
> 
> Edit: With the switch in its old location disabling the filter panel also disabled the "Add filter" panel as well

This should be fixed now.

**Review by nikolas-burkoff — COMMENTED** [review]
2 points:

- The collapse icons can be incorrect if you disable the filter panel when one of the dataset filters is collapsed:

image

- If you have disabled and enabled filters:

image

And then disable and enable the filter panel it doesn't remember the state of the filter panel when it was disabled:

image

Assuming this is the desired behavio(u)r then this is fine.

**Comment by asbates** [comment]
>     * The collapse icons can be incorrect if you disable the filter panel when one of the dataset filters is collapsed:
> 
 I have no idea why because I didn't change anything around these as far as I know. I'll look into it.

>     * If you have disabled and enabled filters: 
> And then disable and enable the filter panel it doesn't remember the state of the filter panel when it was disabled:
> 
> Assuming this is the desired behavio(u)r then this is fine.

This is not desired behavior, at least to me. Actually, I think we shouldn't remove the filter cards at all (#206) which is the root of the problem. However, I don't think it's within the scope of this PR.

**Comment by asbates** [comment]
>     * The collapse icons can be incorrect if you disable the filter panel when one of the dataset filters is collapsed:

This happens on filter panel refactor branch as well so I opened #239

**Review by nikolas-burkoff — APPROVED** [review]
Given that we have #206 and #239 I think this can go in 👍

**Pull request merged**
