### PR TITLE
455 bug in filter card reactivity

### LINKED ISSUE #455: bug in filter card reactivity
Clicking filter card controls triggers toggling of the body.

https://github.com/insightsengineering/teal.slice/assets/114988527/d812f5e6-f74d-498c-b078-5fcbb0ca6db0

```
rm(list = ls())

options("teal.bs_theme" = bslib::bs_theme(version = 3))
devtools::load_all("../teal.slice")
devtools::load_all("../teal")
library(scda)


funny_module <- function (label = "Filter states", datanames = "all") {
  checkmate::assert_string(label)
  module(
    label = label,
    datanames = datanames,
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_states")),
        verbatimTextOutput(ns("filter_calls")),
        actionButton(ns("reset"), "reset_to_default")
      )
    },
    server = function(input, output, session, data, filter_panel_api) {
      checkmate::assert_class(data, "tdata")
      observeEvent(input$reset, set_filter_state(filter_panel_api, default_filters))
      output$filter_states <- renderText({
        logger::log_trace("rendering text1")
        stage1 <- filter_panel_api |> get_filter_state()
        stage2 <- lapply(stage1, as.list)
        stage3 <- yaml::as.yaml(stage2)
        stage3
      })
      output$filter_calls <- renderText({
        logger::log_trace("rendering text2")
        attr(data, "code")()
      })
    }
  )
}

Iris <- iris
levels(Iris$Species) #%<>% toupper()
Iris$Species2 <- Iris$Species
Iris$Species3 <- Iris$Species
Iris$Sepal.Length[1] <- NA
Iris$Sepal.Length[2] <- Inf
Iris$Species3[2] <- NA
attr(Iris[[1]], "label") <- "variable label"
attr(Iris[[2]], "label") <- "variable label"
attr(Iris[[3]], "label") <- "variable label"
attr(Iris[[4]], "label") <- "variable label"
data <- teal_data(
  dataset("iris", Iris),
  dataset("mtcars", mtcars)
)

default_filters <- teal_slices(
  teal_slice("iris", "Sepal.Length", fixed = FALSE, anchored = FALSE),
  teal_slice("iris", "Sepal.Width", sel = c(2.5, 4.0), fixed = FALSE, anchored = TRUE),
  teal_slice("iris", "Petal.Length", sel = c(4.5, 5.1), fixed = TRUE, anchored = FALSE),
  teal_slice("iris", "Petal.Width", sel = c(0.3, 1.8), fixed = TRUE, anchored = TRUE),
  count_type = NULL
)

app <- init(
  data = data,
  modules = list(funny_module(), funny_module("module2")), filter = default_filters
)

runApp(app, launch.browser = TRUE)
```

### PR DESCRIPTION
**Pull request by chlebowa**
Fixes #455 

The div containing the buttons (rewind, restore, remove), which is of class `filter_card_controls`, receives `onclick = "event.stopPropagation();"` property to suppress click registration by containing DOM elements. In order to work with bs5 it also receives `data-bs-toggle = "collapse"` and `data-bs-target = NULL` properties.

Since clicks from buttons do not propagate to the `filter_card_title` element, the body collapsing effect can be applied to the whole `filter_card_header` rather than to `filter_card_title` and `filter_card_summary` separately, removing duplicated code.

### CODE REVIEW

**Comment by kartikeyakirar** [comment]
The issue is resolved in bs3 and bs4 but persists in bs5.


https://github.com/insightsengineering/teal.slice/assets/6700955/9f2d436a-1384-4908-aab2-459b01c2dcc5

**Comment by kartikeyakirar** [comment]
Additionally, there is another unexpected behavior. When you scroll down and make changes to bring the rewind and restore button, clicking on it automatically repositions the page within the dashboard, moving it upwards.

https://github.com/insightsengineering/teal.slice/assets/6700955/6ca22f07-120f-4936-907b-a8586daf0623

This behavior did not exist there before.
(demo from main brach)

https://github.com/insightsengineering/teal.slice/assets/6700955/582775c4-d593-41db-a8c5-450a76ba4cb7

**Comment by chlebowa** [comment]
There is an alternative solution but we would have to forego the animation of filter card toggling so not ideal.

**Comment by kartikeyakirar** [comment]
The solution appears to be great and everything is working as expected. 🚀 

test on code for bs3, bs4 and bs5

```
options("teal.bs_theme" = bslib::bs_theme(version = 3))
options("teal.bs_theme" = bslib::bs_theme(version = 4))
options("teal.bs_theme" = bslib::bs_theme(version = 5))
```

```
rm(list = ls())


devtools::load_all("../teal.slice")
devtools::load_all("../teal")
library(scda)


funny_module <- function (label = "Filter states", datanames = "all") {
  checkmate::assert_string(label)
  module(
    label = label,
    datanames = datanames,
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_states")),
        verbatimTextOutput(ns("filter_calls")),
        actionButton(ns("reset"), "reset_to_default")
      )
    },
    server = function(input, output, session, data, filter_panel_api) {
      checkmate::assert_class(data, "tdata")
      observeEvent(input$reset, set_filter_state(filter_panel_api, default_filters))
      output$filter_states <- renderText({
        logger::log_trace("rendering text1")
        stage1 <- filter_panel_api |> get_filter_state()
        stage2 <- lapply(stage1, as.list)
        stage3 <- yaml::as.yaml(stage2)
        stage3
      })
      output$filter_calls <- renderText({
        logger::log_trace("rendering text2")
        attr(data, "code")()
      })
    }
  )
}

Iris <- iris
levels(Iris$Species) #%<>% toupper()
Iris$Species2 <- Iris$Species
Iris$Species3 <- Iris$Species
Iris$Sepal.Length[1] <- NA
Iris$Sepal.Length[2] <- Inf
Iris$Species3[2] <- NA
attr(Iris[[1]], "label") <- "variable label"
attr(Iris[[2]], "label") <- "variable label"
attr(Iris[[3]], "label") <- "variable label"
attr(Iris[[4]], "label") <- "variable label"
data <- teal_data(
  dataset("iris", Iris),
  dataset("mtcars", mtcars)
)

default_filters <- teal_slices(
  teal_slice("iris", "Sepal.Length", fixed = FALSE, anchored = FALSE),
  teal_slice("iris", "Sepal.Width", sel = c(2.5, 4.0), fixed = FALSE, anchored = TRUE),
  teal_slice("iris", "Petal.Length", sel = c(4.5, 5.1), fixed = TRUE, anchored = FALSE),
  teal_slice("iris", "Petal.Width", sel = c(0.3, 1.8), fixed = TRUE, anchored = TRUE),
  count_type = NULL
)

app <- init(
  data = data,
  modules = list(funny_module(), funny_module("module2")), filter = default_filters
)

runApp(app, launch.browser = TRUE)
```

**Review by kartikeyakirar — APPROVED** [review]

**Pull request merged**
