### PR TITLE
Adds min package version

### PR DESCRIPTION
**Pull request by averissimo**
WIP :: parent issue: https://github.com/insightsengineering/nestdevs-tasks/issues/7

Supersede:
* https://github.com/insightsengineering/teal.slice/pull/332

### 🔴 Checklist for PR Reviewer

[Scheduled 🕰️](https://github.com/insightsengineering/teal.slice/actions/workflows/scheduled.yaml?query=branch%3Averdepcheck_action) _(see comment below)_

- [ ] Tag yourself next to this repo on https://github.com/insightsengineering/nestdevs-tasks/issues/7
- [ ] Package versions are the same or higher than `main`
- [x] Package list is the same
  - Only exception is `rmarkdown` (may have been removed on `Suggests`)
- [x] All packages in `Imports`, `Depends` & `Suggests` are in new section `Config/Needs/verdepcheck`
- [x] Added entry to `NEWS.md`
- [ ] Last `scheduled.yaml` action was run succesfully _(all 4 strategies)_
  - important: it's not the last commit, it's the one that runs 4 `Scheduled 🕰️ / Dependency` actions
- [x] `scheduled.yaml` SHOULD NOT have any push on any branches

### 🔴 What's needed before merging?

This PR depends on some upstream changes that need to be finalized/merged before being ready to review.

#### Change in code

* `verdepcheck.yml` action (see comments)
  - [x] Remove `on: push` section 
  - [x] Change branch to main

#### PRS

- [x] verdepcheck
  * https://github.com/insightsengineering/verdepcheck/pull/24
  * https://github.com/insightsengineering/verdepcheck/pull/26
- [x] verdepcheck-action
  * https://github.com/insightsengineering/r-verdepcheck-action/pull/16

### Changes description

* Adds minimum version for packages `DESCRIPTION`
* Adds `Config/Need/verdepcheck` section in `DESCRIPTION`
* Updates verdepcheck action

### CODE REVIEW

**Comment by m7pr** [comment]
Thanks @averissimo . How often should we do this exercise? Is it going to be scheduled weekly and verify min ver of packages?

**Comment by averissimo** [comment]
@m7pr I believe the idea is for this to be executed weekly per `scheduled.yml`.

This will alert for whenever a new API is used that the min_version doesn't support, but it will also alert to breaking changes that are appearing in GitHub _(so that we can act early on, before the CRAN release of "that" package)_

**Comment by m7pr** [comment]
Sounds great, really cool feature

**Comment by averissimo** [comment]
`max` strategy is failing due to a change in `bslib` package

Reported here: https://github.com/insightsengineering/teal.slice/issues/466

All other strategies are working

[Scheduled 🕰️](https://github.com/insightsengineering/teal.slice/actions/workflows/scheduled.yaml?query=branch%3Averdepcheck_action)

**Comment by m7pr** [comment]
Retriggering the job in Actions menu https://github.com/insightsengineering/teal.slice/actions/runs/6249307143 for verdepcheck branch as I saw last run failed

**Comment by m7pr** [comment]
just heard over the meeting that failure for `max` is fine

**Review by m7pr — APPROVED** [review]

**Pull request merged**
