### PR TITLE
335 remove aliases from package index

### LINKED ISSUE #335: `teal_slice` should show up in package index
The `teal_slice` help topic extensively documents the `teal_slice` and `teal_slices` classes and explains at length how filter states are defined and handled. Although all the functions in that topic are not exported, I believe `teal_slice` should be visible in the package index in RStudio's Help tab.

### PR DESCRIPTION
**Pull request by chlebowa**
Fixes #335 

Package index is built during the installation process but only once the package has been actually installed.
A file is created, `<package>/html/00Index.html`, that is the source for the index page.

Here, a function is added that modifies `html/00Index.html` to remove HTML elements that link to a specified topic through aliases.
The function is called in the loading hook.

`@keywords internal` is removed from all functions that are included in `teal_slice`, `teal_slices`, and `filter_state_api`.

### CODE REVIEW

**Comment by chlebowa** [comment]
Then no changes are made
```
  if (identical(index_file, "") || !isTRUE(utils::file_test("-w", index_file))) {
    return(invisible(FALSE))
  }
```

**Comment by gogonzo** [comment]
I would like this solution if `pkgdown` used installed package index - I run `pkgdown::build_site` and it seems that `pkgdown` build site from the source including all aliases in the rendered site

**Comment by m7pr** [comment]
Maybe for `pkgdown` we need some custom code in `pkgdown.yml` to be executed so that the pkgdown-index gets cleaned the same way it's done for package index.

**Comment by pawelru** [comment]
> Then no changes are made

I am afraid that this would make it working only for subset of users. To my surprise, centrally managed environments is quite popular in the pharma world - even internally we have a BEE environment managed like that.

Is this really the only way to address this problem? Can it be done with modification of roxygen tags? Maybe we can slightly change the approach of documentation to obey this issue? Just thinking loudly...

**Comment by m7pr** [comment]
I actually like the idea, if this plays with `pkgdown` as it also clears aliases for `filter-panel-api` that are also duplicated (4 times).

**Comment by chlebowa** [comment]
`pkgdown` provides a way to exclude a topic from the reference but raises an error if you do :unamused:

**Comment by chlebowa** [comment]
> Is this really the only way to address this problem? Can it be done with modification of roxygen tags? Maybe we can slightly change the approach of documentation to obey this issue? Just thinking loudly...

Be my guest.

**Comment by m7pr** [comment]
@pawelru 

> Can it be done with modification of roxygen tags? 

It's a bigger problem and we research multiple approaches. You can read https://github.com/insightsengineering/teal.slice/issues/335 and other PR https://github.com/insightsengineering/teal.slice/pull/565

**Comment by pawelru** [comment]
> > Can it be done with modification of roxygen tags?
> 
> It's a bigger problem and we researched multiple approaches. You can read #335 and other PR #565

> > Is this really the only way to address this problem? Can it be done with modification of roxygen tags? Maybe we can slightly change the approach of documentation to obey this issue? Just thinking loudly...
> 
> Be my guest.

I tried to avoid going deeper if possible. I need to focus on something else at the current moment. I can do that but a little bit later. Just wanted to flag this out for you in case you are unaware.

**Comment by chlebowa** [comment]
> `pkgdown` provides a way to exclude a topic from the reference but raises an error if you do 😒

This seems to be a bug that was supposedly fixed in 2022. I will raise the issue again but even if they do fix it, I don't think they will do it soon.

**Comment by chlebowa** [comment]
> I tried to avoid going deeper if possible. I need to focus on something else at the current moment. I can do that but a little bit later. Just wanted to flag this out for you in case you are unaware.

We are four days in, join us when you can :wink:

**Comment by m7pr** [comment]
>> pkgdown provides a way to exclude a topic from the reference but raises an error if you do 😒

> This seems to be a bug that was supposedly fixed in 2022. I will raise the issue again but even if they do fix it, I don't think they will do it soon

Maybe we can run it with `suppressWarnings/suppressMessages` to avoid having it be displayed during GHA builds?

**Comment by chlebowa** [comment]
> Maybe we can run it with `suppressWarnings/suppressMessages` to avoid having it be displayed during GHA builds?

```
-- Building function reference -------------------------------------------------
Error: 
! in callr subprocess.
Caused by error in `check_missing_topics(rows, pkg)`:
! All topics must be included in reference index
✖ Missing topics: filter_state_api
ℹ Either add to _pkgdown.yml or use @keywords internal
ℹ See `$stdout` for standard output.
Type .Last.error to see the more details.
```

Good luck.

**Comment by m7pr** [comment]
Got it, how do you run it? Did you add `reference` section to `pkgdown.yml` and run `build_site` or did you use `build_reference`?

**Comment by chlebowa** [comment]
image

**Comment by m7pr** [comment]
Looks like promising path!

**Comment by chlebowa** [comment]
@pawelru Re: file permissions, I forgot to mention that a package is test-loaded _during installation_ and the index file is modified then.

**Comment by pawelru** [comment]
> @pawelru Re: file permissions, I forgot to mention that a package is test-loaded _during installation_ and the index file is modified then.

That's great to hear. It means that my concern is not valid and I no longer see any blockers. However, I do encourage you to continue with looking for alternatives and do compare different approaches. I personally would prefer a fix to be incorporated in the already built package compared to apply fix on install. That's of course as long as it is possible.

Now I cannot say it's buggy or incorrect. It's just non-standard and I am afraid that I am just unable to assess all possible outcomes or edge-cases. Why I do care? Non-standard ways of working introduce some difficulty and requires some/deep knowledge and generally speaking i do want to have a low and cheap maintenance code. I really hope you know what I am mean.
I did a very quick search on GH CRAN mirror: https://github.com/search?q=org%3Acran+path%3A*.R+00Index.html&type=code
Out of 26k+ repos only 16 of them are using `00Index.html` file and looking briefly most of them do read only. (It looks like only one `knitr` does write but I don't want to spend my time trying to understand it - that's not the point to get an exact number).

I know I am sitting on a very comfy reviewer position but I think that there is enough IQ points already there to came up with something good :) You are all clever folks and I believe in you 💪

**Comment by chlebowa** [comment]
> Out of 26k+ repos only 16 of them are using `00Index.html` file

False.
The file is built by internal functions of the `tools` package upon installation. Every package that has a package index page (which I believe means virtually every package in existence) has that page. Why the page is not built with the `INDEX` file from the package root directory, which can be modified in the source package - I don't know.

> I do encourage you to continue with looking for alternatives and do compare different approaches.

Believe me, I tried. This is the best I was able to come up with. See https://github.com/insightsengineering/teal.slice/pull/568 for an inferior alternative.

Now, is this bulletproof? I don't know. For example, my way of dropping rows from the HTML file is rather primitive and makes some assumptions.

**Comment by pawelru** [comment]
Ahhh I knew you will find something in my statement :) I really tried my best! Let me correct myself. That statement should go as follows

Out of 26k+ packages on CRAN, only 16 are _accessing_ `00Index.html` file in its sources. _Accessing_ for _read_ / _write_ or any other purpose. They all might _have_ it (and _use_ it) but only very small number of packages is doing actual modifications.

Anyway, that's just to show why I think it's non-standard. I will try to have a look at this but in the middle of next week the earliest.

**Comment by chlebowa** [comment]
> Out of 26k+ packages on CRAN, only 16 are _accessing_ `00Index.html` file in its sources.

Fair :smiley: One of the reasons it is rarely accessed is it does not exist in the source. I agree, it is nonstandard.

**Comment by chlebowa** [comment]
I raised an issue in the `pkgdown` repo but no help will be coming.

This is what I have been able to accomplish with the current state of affairs:

image

image


I suggest we apply it as is.

**Pull request closed without merging**
