### PR TITLE
init filter card design

### LINKED ISSUE #129: [Feature Request]: FilterState to not show shiny inputs by default
part of #48 
### Feature description

Please see the [wireframe](https://drive.google.com/file/d/1jYjYZR6Yqtfv7ZzMfBMa2T5xYIwWmVL7/view?usp=sharing)

1. Shiny inputs should not be visible by default. So called filter-card-summary (ui of the FilterState) should displayed - showing summarized information of the filer-state.
2. User clicks the active button in filter-card-summary to trigger change from filter-card-summary to filter-card-interactive. (Button can be a small gear icon or the card itself).
3. filter-card-interactive is rendered each time it's triggered to show (selection is based on the current state). User can change the values in filter-card-interactive and they are not propagated immediately until one clicks save. Once saved card turns back again to filter-card-summary with a new values. Thanks to updating values of the interactive selection after save only, we don't need a set_selected_reactive anymore (please see below).

--------

Important: Please be aware of how the FilterState$private$selected can be changed. Please see `help(teal.slice:::FilterState)` and go to the modyfying state, you'll see following image:

image

Filter states can be changed in three ways. See example [FilterState$server](https://github.com/insightsengineering/teal.slice/blob/e866d4dd6f7d3d3cec23725b1df8adabc8e506b6/R/FilterState.R#L1140):
- In the interactive session by directly specifying values of selected, keep_na or keep_inf using set_state method (to update all at once), or using set_selected, set_keep_na or set_keep_inf
- In a teal application by changing appropriate inputs
- Using methods set_selected_reactive, set_keep_na_reactive, set_keep_inf_reactive which serves as a programmatic API.

Important improvement would be to remove area in the dashed rectangle which will simplify [this](https://github.com/insightsengineering/teal.slice/blob/e866d4dd6f7d3d3cec23725b1df8adabc8e506b6/R/utils.R#L196) process.

### PR DESCRIPTION
**Pull request by asbates**
Closes #129 

Start implementing filter card design. This is a _very_ minimal start so don't judge :)

* Only `FilterStateLogical` is implemented
* Collapse/expand not working. I need to refactor the JS I have. 
* Needs styling
* There's a good deal of room for refactoring the UI/server components and where they live. But that might be better as a second stage.

I don't think this is ready to start incorporating anywhere yet. But I wanted to share what I do have.

### CODE REVIEW

**Comment by gogonzo** [comment]
This looks amazing @asbates 
image

**Comment by asbates** [comment]
Filter accordion is almost working. After app launch, you need to open the browser console and type 

```js
id = document.getElementsByClassName('filter-card-container')[0].id 
activateHeaders(id) 
```


I'm trying to find a good place in the code to make this work on launch. It all boils down to event listeners. But I'm having trouble finding the timing to add them. On launch, the elements (filter card headers) don't exist so no listeners can be attached. When the cards are [inserted](https://github.com/insightsengineering/teal.slice/blob/6a251976b853cee320cd0bff9217adcebe13fcc0/R/FilterStates.R#L441), we can't add the listeners right away because there is a delay between `shiny::insertUI` and the element existing.

**Comment by asbates** [comment]
@gogonzo With today's push the accordion should be working correctly. I haven't tested thoroughly yet though.

**Comment by asbates** [comment]
closing this for #181

**Pull request closed without merging**
