### PR TITLE
`ui` to UI in documentation

### PR DESCRIPTION
**Pull request by averissimo**
Changes after feedback on #524 (too big to be merged directly)

- UI was already in `inst/WORDLIST`
- Added `ui_active` in `srv_active` parameter documentation and applied this to other `srv_*` methods.

### CODE REVIEW

**Comment by kartikeyakirar** [comment]
@averissimo PR looks great. thanks for catching and adding `ui_active` in `srv_active`. One minor thing can you check the instance of `server` there is one left in FilterpanelApi.R

**Comment by averissimo** [comment]
@kartikeyakirar :heavy_check_mark:

**Comment by averissimo** [comment]
@kartikeyakirar :heavy_check_mark:

**Review by kartikeyakirar — APPROVED** [review]
👍

**Pull request merged**
